### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by dieterjw** [InternetConnectionMonitor/icm-public#101]
I would like to have Internet Connection Monitor as an Android app. I haven't found something comparable that is as easy to . I use it simply to monitor the reliability of my Internet connection which is not very good at the moment. A log file would be great as a proof to my provider.

I like the idea to use an old smartphone for this task. I have one lying around and it uses less energy than my PC. My WiFi connection is reliable so I see no additional problems.

Greetings, Dieter

**Comment by dmishh** [comment]
Hi @dieterjw, this request is already here #86 
I put your comment there for context, feel free to upvote
