### ISSUE TITLE
Testing Frequency

### ISSUE THREAD

**Issue by PXB99** [InternetConnectionMonitor/icm-public#60]
How do I change the testing frequency?

**Comment by PXB99** [comment]
I have the extension installed and it opens to the Internet Connection Monitor page. There is no "Settings" link or button.
![Internet Connections log page](https://user-images.githubusercontent.com/55961291/223445829-2ba9796d-a1bc-4657-98c1-fa07a68e5135.JPG)

**Comment by dmishh** [comment]
This is the connection log - on the screenshot you sent. How did you open that "Internet connection log" window?

**Comment by dmishh** [comment]
The image I posted before is the actual Extension page (or the main popup) that opens when you click on the icon in the extensions bar.

**Comment by PXB99** [comment]
Thanks Dmytro,
When I downloaded and installed it in Chrome, I clicked on "open" and it opened in a tab so I pinned it by right-clicking on the tab.
I did not know I needed to click on the icon in the Extensions bar to access the Settings.
Peter B.
