### ISSUE TITLE
Powerring down my Laptop

### ISSUE THREAD

**Issue by PXB99** [InternetConnectionMonitor/icm-public#61]
Hello, I have ICM installed on my Laptop, if I power down the laptop overnight does ICM show that as a disconnect?
Thanks.

**Comment by Epaphras47** [comment]
I had a case where my Windows machine locked up and I had to hold the power button down to kill it.  When it restarted, it came up online but the "Downtime, total" counter is stuck counting and messing up the statistics.

**Comment by dmishh** [comment]
@PXB99 Yes, it should work, but the mechanism of tracking the disconnects while the computer is in sleep has not been thoroughly tested. Macs, for example, wake up every couple minutes and ICM checks the connection properly. But do not rely on precise measurement during the computer sleep - precision is not guaranteed, keep the computer running

**Comment by dmishh** [comment]
@Epaphras47 it may happen, in that case, just turn off Wi-Fi and turn it back on. It should fix the issue
