### ISSUE TITLE
Multiple issues with reporting downtime

### ISSUE THREAD

**Issue by pruchkin2** [InternetConnectionMonitor/icm-public#62]
provider is xfinity, and thru Arris 8200 modem connected to ASUS router

1. Showed bogus outage 3/24-28
2. Didn't reflect actual 21 hr outage properly from 4/1 11 pm ET to 4/2 7pm 

See attached screenshot
![ICM Issues](https://user-images.githubusercontent.com/27218191/229510002-cc1191ee-96c3-46df-a5dd-f368b9f6cf40.png)

**Comment by Epaphras47** [comment]
I just reported a similar issue.  Mine, I believe, got triggered when my PC locked up on me.  Ever since the reboot, the downtime keeps counting even though I'm "online".

**Comment by dmishh** [comment]
@pruchkin2 @Epaphras47 I'll keep an eye on these double-disconnects

By that time, @pruchkin2 can you please provide more context (if you remember) about the disconnect on 4/1:
* How do you know it was disconnected at 11pm and reconnected the next day on 7pm? Any logs? You just remember?
* Do you run ICM on a laptop or desktop? Was it asleep or up?

**Comment by dmishh** [comment]
Closing this for now
