### ISSUE TITLE
Feature request: show public IP address

### ISSUE THREAD

**Issue by sebastienbo** [InternetConnectionMonitor/icm-public#65]
- [x] Get IP via ipify.org
- [x] Fallback
- [x] Translations
- [x] IP in popup
- [x] IP in stats
- [x] IP in log
- [x] IP in monitor
- [x] i18n
- [x] Manual test cases

Original request
------
Hi,

it would be handy if it would show the public ip adress of the user under the statistics.
This could help understanding what might be wrong with the connection.
It is also handy to know on which internet connection we are connected to

Currently i have to install another chrome extension that does just that:
https://chrome.google.com/webstore/detail/my-ip-address/monhkdcehmbdgkhgpccaccbbcgcfpjkd

it would be handy to only need one extension instead of 2

**Comment by dmishh** [comment]
Possibly using a free service for obtaining IP address https://www.ipify.org/
