### ISSUE TITLE
Downtime counter issue

### ISSUE THREAD

**Issue by Epaphras47** [InternetConnectionMonitor/icm-public#67]
After a connection loss and recovery, the downtime counter still counts while the status is "online".  The two screen captures below show that both the online and downtime counters are running at the same time.

![image](https://github.com/InternetConnectionMonitor/icm-public/assets/29456485/f8b112fd-9a7d-47ae-ad8e-72abb88b7b77)
![image](https://github.com/InternetConnectionMonitor/icm-public/assets/29456485/72f5d6ed-6195-404b-9704-bc3de9783852)

**Comment by Epaphras47** [comment]
I tried restarting my machine to see if it would rectify it but with no luck.

**Comment by Epaphras47** [comment]
Disabling the extension and reenabling it does not rectify it either.

**Comment by Epaphras47** [comment]
The circumstance that may have got it in this state is that my Windows machine locked up and I had to hold the power button down to kill it.  When it restarted, it came up online but the "Downtime, total" counter is stuck counting and messing up the statistics.  This is an uncommon but possible condition.  It appears the only way to resolve this case is to uninstall and reinstall.  I haven't done that because I also have it running on my Mac.  I wanted to leave it running for you in case you wanted any additional information.

![image](https://github.com/InternetConnectionMonitor/icm-public/assets/29456485/2e839c42-741e-405a-9c19-8caa05cea706)

**Comment by dmishh** [comment]
@Epaphras47 that's a very strange behavior. Can you try to disable / enable Wi-Fi? It should theoretically solve the issue

**Comment by dmishh** [comment]
Fixed in 5.0, will be released by the end of Dec 2023
