### ISSUE TITLE
Wish drop-down menu showed disconnects for past 7 and 30 days

### ISSUE THREAD

**Issue by RobPNeff** [InternetConnectionMonitor/icm-public#75]
- [x] Calculate stats for 4 periods: Today, 7 days, 30 days, All time
- [x] Remove All time stats from popup
- [x] Add Disconnects, Availability, Downtime stats for 4 periods to log, monitor and stats pages
- [x] i18n
- [x] Test for the function that calculates stats for the chosen date
- [x] Manual test cases

Original request
------
I really appreciate the ICM tool having been developed.  I just wish that it showed a little more history in the main menu.  It shows only "Todays" and "Total" Disconnects/Availability/Downtime.   My today was 0 and my Total was 9000+.  This doesn't give me a good picture of my ISP & Wifi reliability.  If the tool showed the past 7 and 28 days, it would be much easier for a user to see when the issue started and if there was a negative or positive trend.

**Comment by dmishh** [comment]
Thanks, @RobPNeff 
I'll think about it, maybe improve the stats page to give the user more insights into the connection issues timeline

**Comment by dmishh** [comment]
Probably, convert the stats to a table and put on all stats-like pages
<img width="786" alt="Screenshot 2024-05-05 at 20 01 21" src="https://github.com/InternetConnectionMonitor/icm-public/assets/822562/32fe887f-6016-4d96-a35f-39ccaf581568">
