### ISSUE TITLE
Replace the Connection and Make new request for public network to the internet connection monitor....

### ISSUE THREAD

**Issue by mohit98368** [InternetConnectionMonitor/icm-public#76]
Now: 03/14/2024 8:19:23 PM
Online for: 0:07:52
Latency: 93 ms
Disconnects, today: 2
Availability, today: 99.95%
Downtime, today: 0:00:36
Disconnects, total: 10
Availability, total: 99.99%
Downtime, total: 0:02:51

**Comment by mohit98368** [comment]
Please comment CPFR#....

**Comment by dmishh** [comment]
Banned for spam
