### ISSUE TITLE
❓ 🙋‍♂️ Is the ICM Chrome Extension open-sourced?

### ISSUE THREAD

**Issue by Cheezmeister** [InternetConnectionMonitor/icm-public#78]
This repo seems to contain the content for https://internetmon.org

The other repo in [this org](https://github.com/InternetConnectionMonitor) contains simply a [README](https://github.com/InternetConnectionMonitor/.github/blob/main/profile/README), capturing mostly the same information.

Where can I find the source code and/or logic that does the actual work here?

**Comment by dmishh** [comment]
Hey @Cheezmeister, the source code of the extension is not and will not be open to the public. I encountered numerous attempts to copy the extension and publish it under a different name.
